-- AlterEnum - add new values (each must be committed before use)
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'SCREENING';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'TECH_SCREENING';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'TODO';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'MEETUP';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'NONE';
